apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath  # local; gp3 in EKS
  resources:
    requests:
      storage: 5Gi
